# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HW1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.setCentralWidget = QtWidgets.QWidget(MainWindow)
        self.setCentralWidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 361, 191))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 80, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 130, 121, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(170, 20, 171, 151))
        self.groupBox_6.setObjectName("groupBox_6")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox.setGeometry(QtCore.QRect(20, 50, 131, 31))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 90, 131, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(30, 30, 101, 16))
        self.label_8.setObjectName("label_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(590, 30, 171, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 40, 141, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(420, 150, 311, 371))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 20, 271, 291))
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 20, 231, 201))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label = QtWidgets.QLabel(self.groupBox_9)
        self.label.setGeometry(QtCore.QRect(10, 30, 51, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_9)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_9)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 51, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_9)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 51, 31))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit.setGeometry(QtCore.QRect(60, 40, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 70, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 120, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_4.setGeometry(QtCore.QRect(60, 160, 113, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_9)
        self.label_5.setGeometry(QtCore.QRect(180, 40, 58, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_9)
        self.label_6.setGeometry(QtCore.QRect(180, 120, 58, 15))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_9)
        self.label_7.setGeometry(QtCore.QRect(180, 160, 58, 15))
        self.label_7.setObjectName("label_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 240, 231, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 320, 231, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 230, 351, 331))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 80, 241, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_12.setGeometry(QtCore.QRect(30, 130, 241, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_13.setGeometry(QtCore.QRect(30, 180, 241, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_14.setGeometry(QtCore.QRect(30, 270, 241, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_15.setGeometry(QtCore.QRect(30, 30, 241, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(10, 240, 111, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 230, 181, 31))
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setMaxLength(4)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 30, 171, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 50, 151, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(450, 530, 101, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(590, 530, 101, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "1. Calibration"))
        self.pushButton.setText(_translate("MainWindow", "1.1 Find Corners"))
        self.pushButton_2.setText(_translate("MainWindow", "1.2 Intrinsic"))
        self.pushButton_3.setText(_translate("MainWindow", "1.4 Distortion"))
        self.groupBox_6.setTitle(_translate("MainWindow", "1.3 Extrinsic"))
        self.pushButton_4.setText(_translate("MainWindow", "1.3 Extrinsic"))
        self.label_8.setText(_translate("MainWindow", "Select Image"))
        self.groupBox_3.setTitle(_translate("MainWindow", "4. Find Contour"))
        self.pushButton_5.setText(_translate("MainWindow", "4.1 Find Contour"))
        self.groupBox_4.setTitle(_translate("MainWindow", "3. Image Transformation"))
        self.groupBox_8.setTitle(_translate("MainWindow", "3.1 Rot, scale ,Translate"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Parameters"))
        self.label.setText(_translate("MainWindow", "Angle:"))
        self.label_2.setText(_translate("MainWindow", "Scale:"))
        self.label_3.setText(_translate("MainWindow", "Tx:"))
        self.label_4.setText(_translate("MainWindow", "Ty:"))
        self.label_5.setText(_translate("MainWindow", "deg"))
        self.label_6.setText(_translate("MainWindow", "pixel"))
        self.label_7.setText(_translate("MainWindow", "pixel"))
        self.pushButton_7.setText(_translate("MainWindow", "3.1 Rot, scale ,Translate"))
        self.pushButton_8.setText(_translate("MainWindow", "3.2 Perspective Transform"))
        self.groupBox_5.setTitle(_translate("MainWindow", "5. Train Cifar-10 Classifier"))
        self.pushButton_11.setText(_translate("MainWindow", "5.2 Show Hyperparametters"))
        self.pushButton_12.setText(_translate("MainWindow", "5.3 Train 1 Epoch"))
        self.pushButton_13.setText(_translate("MainWindow", "5.4 Show Training Result"))
        self.pushButton_14.setText(_translate("MainWindow", "5.5 Interface"))
        self.pushButton_15.setText(_translate("MainWindow", "5.1 Show Train Images"))
        self.label_9.setText(_translate("MainWindow", "Test Image Index:"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "(0~9999)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2. Augumented Reality"))
        self.pushButton_6.setText(_translate("MainWindow", "2.1 Augumented Reality"))
        self.pushButton_9.setText(_translate("MainWindow", "OK"))
        self.pushButton_10.setText(_translate("MainWindow", "Cancel"))


if __name__ == '__main__':  
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()

    ui.setupUi(MainWindow) 
    MainWindow.show()
    sys.exit(app.exec_()) 